# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  # - osx
julia:
  - 1.3
  - nightly
matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true
notifications:
  email: false

# Only build branches via PR to avoid running CI twice.
# https://docs.travis-ci.com/user/conditional-builds-stages-jobs
# https://docs.travis-ci.com/user/conditions-v1
if: branch = master OR tag IS present OR type != push

before_install:
  - unset JULIA_PROJECT
  - julia -e 'using Pkg; pkg"add https://github.com/tkf/Run.jl"'
install:
  - julia -e 'using Run; Run.prepare("test/environments/main")'
script:
  - julia -e 'using Run; Run.test(project="test/environments/main")'
after_success:
  - julia -e 'using Run; Run.after_success_test()'
jobs:
  include:
    - julia: 1.0
      os: linux
      install:
        - julia -e 'using Run; Run.prepare("test/environments/jl10")'
      script:
        - julia -e 'using Run; Run.test(project="test/environments/jl10")'
    - stage: Documentation
      install:
        - julia -e 'using Run; Run.prepare_docs()'
      script:
        - julia -e 'using Run; Run.docs()'
      after_success: skip
