name = "Kaleido"
uuid = "caafb194-7e8d-11e9-2724-d5981dd0806d"
authors = ["Takafumi Arakaki <aka.tkf@gmail.com>"]
version = "0.2.8"

[deps]
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"

[compat]
Requires = "0.5, ^1.0"
Setfield = "0.3, 0.4, 0.5, 0.6, 0.7, ^0.8"
julia = "^1.0"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StaticNumbers = "c5e4b96a-f99f-5557-8ed2-dc63ef9b5131"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TransformVariables = "84d833dd-6860-57f9-a1a7-6da5db126cff"

[targets]
test = ["Aqua", "Documenter", "InteractiveUtils", "StaticArrays", "StaticNumbers", "Test", "TransformVariables"]
